### ISSUE TITLE
ابهام در پکیج جلالی

### ISSUE THREAD

**Issue by mimsinn** [ariaieboy/filament-jalali-datetime#6]
با عرض سلام و خسته نباشید خدمت شما دوست عزیز.
من در یک پروژه فیلامنتی نیازمند استفاده از تاریخ جلالی داشتم و از پکیج‌های شما استفاده کردم (form , table) در هنگام ذخیره تاریخ ، تاریخ به صورت میلادی ذخیره می‌شود در پایگاه‌داده برای اینکه به صورت جلالی ذخیره شود راه‌حلی وجود دارد.همینطور برای نمایش که از jalaliDateTimeColumn استفاده می‌شود اگر از date() یا هر چیز دیگری استفاده کنم با خطای invalid value range مواجه می‌شوم. بدون استفاده از date مقدار داخل دیتابیس را نمایش میدهد که به صورت میلادی است که میخواهم شمسی باشد.

![image png(2)](https://github.com/user-attachments/assets/64349539-1463-40b5-b1c1-dc91f0c9f788)

![image png(1)](https://github.com/user-attachments/assets/e650ba18-d096-4b7e-a36a-6d8e5909b341)

**Comment by ariaieboy** [comment]
سلام خدمت شما بهتر بود برای هرکدوم از سوالات و مشکلاتتون یک ایشو جدا ایجاد میکردید.
خیر روشی وجود نداره که پکیج تاریخ جلالی را برگردونه به دیتابیس و برنامه ای هم برای افزودن این قابلیت نداریم. چراکه کلا توصیه نمیشه تاریخ جلالی در دیتابیس ذخیره بشه. بهتر هست تاریخ به صورت میلادی ذخیره بشه و هرجا لازم بود تبدیل بشه به جلالی.
در مورد خطایی هم که دریافت میکنید باید مقداری که داخل دیتابیس ذخیره شده را ببینید چی هست. 
یک ریپو با حداقل کد مورد نیاز که این خطا را نمایش بده ایجاد کنید و لینک ریپو را اینجا قرار بدید تا بررسی بشه.

**Comment by mimsinn** [comment]
باتشکر از پیگیری شما
بله باید به نوع داده‌ای که در دیتابیس ذخیره شده است توجه شود. زیرا تاریخ‌ها از قبل به صورت varchar ذخیره شده بودند که با این نوع داده تداخل پیدا می‌کرد.
